# frozen_string_literal: true

require:
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.2

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
  Max: 30
