# frozen_string_literal: true

require:
#  - rubocop-rspec

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
  Max: 30